name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/build
    - name: Build package
      run: |
        echo Building package with version ${{ github.event.release.tag_name }}
        poetry version ${{ github.event.release.tag_name }}
        poetry install
        poetry build
      shell: bash
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
